services:
  web:
    gpus: all
    environment:
      - SLIS_MATCHER_BACKEND=cudf
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  worker:
    gpus: all
    environment:
      - SLIS_MATCHER_BACKEND=cudf
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility