services:
  # Service Redis
  redis:
    image: redis:7-alpine
    container_name: slis_redis
    ports:
      - "6379:6379"

  # Service Flask d
  web:
    build: .
    container_name: slis_web
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SLIS_DEV_FAST_MODE=0
    depends_on:
      - redis
      - worker
    volumes:
      - .:/app

  # Service Celery
  worker:
    build: .
    container_name: slis_worker
    restart: always
    command: celery -A slis.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SLIS_DEV_FAST_MODE=0
    depends_on:
      - redis
    volumes:
      - .:/app